In [185]:
import pandas as pd
import numpy as np

In [186]:
df = pd.read_csv("dataset/student-data-2.csv")
df.head()

,Student Number,Gender,Age,Degree,Year Graduated,CGPA,Average Prof Grade,Average Elec Grade,OJT Grade,Leadership POS,...,Sales Management Skills,Artificial Intelligence Skills,Cybersecurity Skills,Circuit Design Skills,Communication Systems Skills,Problem-Solving Skills,Clinical Skills,Patient Care Skills,Health Assessment Skills,Emergency Response Skills
0,25-00001,Female,22,BSIT,2021,1.96,83.15,82.90,84.31,No,...,NaN,NaN,93.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,25-00002,Female,21,BSIT,2021,3.41,83.83,84.81,81.60,No,...,NaN,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25-00003,Female,23,BSIT,2021,2.44,95.16,88.31,76.36,No,...,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25-00004,Female,22,BSEd-Filipino,2018,1.83,80.97,81.46,91.09,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25-00005,Male,22,BSCS,2019,1.92,84.97,88.81,88.25,No,...,NaN,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 56 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Student Number                           1000 non-null   object
 1   Gender                                   1000 non-null   object
 2   Age                                      1000 non-null   int64
 3   Degree                                   1000 non-null   object
 4   Year Graduated                           1000 non-null   int64
 5   CGPA                                     1000 non-null   float64
 6   Average Prof Grade                       1000 non-null   float64
 7   Average Elec Grade                       1000 non-null   float64
 8   OJT Grade                                1000 non-null   float64
 9   Leadership POS                           1000 non-null   object
 10  Act Member POS                           1000 non-null   object
 11  Soft Skills Ave                          1000 non-null   float64
 12  Hard Skills Ave                          1000 non-null   float64
 13  Auditing Skills                          107 non-null    float64
 14  Budgeting & Analysis Skills              107 non-null    float64
 15  Classroom Management Skills              152 non-null    float64
 16  Cloud Computing Skills                   241 non-null    float64
 17  Curriculum Development Skills            152 non-null    float64
 18  Data Structures & Algorithms             241 non-null    float64
 19  Database Management Skills               340 non-null    float64
 20  Educational Technology Skills            152 non-null    float64
 21  Financial Accounting Skills              107 non-null    float64
 22  Financial Management Skills              160 non-null    float64
 23  Java Programming Skills                  340 non-null    float64
 24  Leadership & Decision-Making Skills      160 non-null    float64
 25  Machine Learning Skills                  241 non-null    float64
 26  Marketing Skills                         160 non-null    float64
 27  Networking Skills                        340 non-null    float64
 28  Programming Logic Skills                 241 non-null    float64
 29  Python Programming Skills                340 non-null    float64
 30  Software Engineering Skills              241 non-null    float64
 31  Strategic Planning Skills                160 non-null    float64
 32  System Design Skills                     340 non-null    float64
 33  Taxation Skills                          107 non-null    float64
 34  Teaching Skills                          152 non-null    float64
 35  Web Development Skills                   340 non-null    float64
 36  Statistical Analysis Skills              0 non-null      float64
 37  English Communication & Writing Skills   79 non-null     float64
 38  Filipino Communication & Writing Skills  73 non-null     float64
 39  Early Childhood Education Skills         0 non-null      float64
 40  Customer Service Skills                  0 non-null      float64
 41  Event Management Skills                  0 non-null      float64
 42  Food & Beverage Management Skills        0 non-null      float64
 43  Risk Management Skills                   107 non-null    float64
 44  Innovation & Business Planning Skills    87 non-null     float64
 45  Consumer Behavior Analysis               73 non-null     float64
 46  Sales Management Skills                  73 non-null     float64
 47  Artificial Intelligence Skills           241 non-null    float64
 48  Cybersecurity Skills                     340 non-null    float64
 49  Circuit Design Skills                    0 non-null      float64
 50  Communication Systems Skills             0 non-null      float64
 51  Problem-Solving Skills                   0 non-null      float64
 52  Clinical Skills                          0 non-null      float64
 53  Patient Care Skills                      0 non-null      float64
 54  Health Assessment Skills                 0 non-null      float64
 55  Emergency Response Skills                0 non-null      float64
dtypes: float64(49), int64(2), object(5)
memory usage: 437.6+ KB

In [188]:
df.describe()

,Age,Year Graduated,CGPA,Average Prof Grade,Average Elec Grade,OJT Grade,Soft Skills Ave,Hard Skills Ave,Auditing Skills,Budgeting & Analysis Skills,...,Sales Management Skills,Artificial Intelligence Skills,Cybersecurity Skills,Circuit Design Skills,Communication Systems Skills,Problem-Solving Skills,Clinical Skills,Patient Care Skills,Health Assessment Skills,Emergency Response Skills
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,107.000000,107.000000,...,73.000000,241.000000,340.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,21.517000,2021.26700,2.324290,84.693250,84.85681,85.033660,79.954800,79.919400,85.009346,84.457944,...,83.465753,84.784232,85.244118,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.238242,2.01737,0.739508,5.998766,5.86027,5.864912,7.725888,7.940358,9.335968,8.917103,...,9.169821,9.000644,8.940435,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,19.000000,2018.00000,1.020000,70.000000,70.00000,70.000000,60.000000,60.000000,70.000000,70.000000,...,70.000000,70.000000,70.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,21.000000,2020.00000,1.820000,80.547500,80.86000,81.095000,74.300000,74.600000,76.000000,76.500000,...,75.000000,77.000000,78.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,21.500000,2021.00000,2.190000,84.855000,84.89000,85.030000,80.200000,80.100000,85.000000,85.000000,...,83.000000,84.000000,85.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,22.000000,2023.00000,2.750000,88.805000,88.78500,89.107500,85.100000,85.525000,94.000000,91.500000,...,89.000000,92.000000,93.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,26.000000,2024.00000,4.990000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [189]:
df.isna().sum()

Student Number                                0
Gender                                        0
Age                                           0
Degree                                        0
Year Graduated                                0
CGPA                                          0
Average Prof Grade                            0
Average Elec Grade                            0
OJT Grade                                     0
Leadership POS                                0
Act Member POS                                0
Soft Skills Ave                               0
Hard Skills Ave                               0
Auditing Skills                             893
Budgeting & Analysis Skills                 893
Classroom Management Skills                 848
Cloud Computing Skills                      759
Curriculum Development Skills               848
Data Structures & Algorithms                759
Database Management Skills                  660
Educational Technology Skills               848
Financial Accounting Skills                 893
Financial Management Skills                 840
Java Programming Skills                     660
Leadership & Decision-Making Skills         840
Machine Learning Skills                     759
Marketing Skills                            840
Networking Skills                           660
Programming Logic Skills                    759
Python Programming Skills                   660
Software Engineering Skills                 759
Strategic Planning Skills                   840
System Design Skills                        660
Taxation Skills                             893
Teaching Skills                             848
Web Development Skills                      660
Statistical Analysis Skills                1000
English Communication & Writing Skills      921
Filipino Communication & Writing Skills     927
Early Childhood Education Skills           1000
Customer Service Skills                    1000
Event Management Skills                    1000
Food & Beverage Management Skills          1000
Risk Management Skills                      893
Innovation & Business Planning Skills       913
Consumer Behavior Analysis                  927
Sales Management Skills                     927
Artificial Intelligence Skills              759
Cybersecurity Skills                        660
Circuit Design Skills                      1000
Communication Systems Skills               1000
Problem-Solving Skills                     1000
Clinical Skills                            1000
Patient Care Skills                        1000
Health Assessment Skills                   1000
Emergency Response Skills                  1000
dtype: int64

In [190]:
df = df.drop(columns=['Student Number'])
df = df.drop(columns=df.columns[df.isna().sum() == len(df)])
df.head()

,Gender,Age,Degree,Year Graduated,CGPA,Average Prof Grade,Average Elec Grade,OJT Grade,Leadership POS,Act Member POS,...,Teaching Skills,Web Development Skills,English Communication & Writing Skills,Filipino Communication & Writing Skills,Risk Management Skills,Innovation & Business Planning Skills,Consumer Behavior Analysis,Sales Management Skills,Artificial Intelligence Skills,Cybersecurity Skills
0,Female,22,BSIT,2021,1.96,83.15,82.90,84.31,No,No,...,NaN,96.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.0
1,Female,21,BSIT,2021,3.41,83.83,84.81,81.60,No,No,...,NaN,79.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0
2,Female,23,BSIT,2021,2.44,95.16,88.31,76.36,No,No,...,NaN,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0
3,Female,22,BSEd-Filipino,2018,1.83,80.97,81.46,91.09,Yes,No,...,98.0,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Male,22,BSCS,2019,1.92,84.97,88.81,88.25,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,NaN

In [191]:
df.isna().sum()

Gender                                       0
Age                                          0
Degree                                       0
Year Graduated                               0
CGPA                                         0
Average Prof Grade                           0
Average Elec Grade                           0
OJT Grade                                    0
Leadership POS                               0
Act Member POS                               0
Soft Skills Ave                              0
Hard Skills Ave                              0
Auditing Skills                            893
Budgeting & Analysis Skills                893
Classroom Management Skills                848
Cloud Computing Skills                     759
Curriculum Development Skills              848
Data Structures & Algorithms               759
Database Management Skills                 660
Educational Technology Skills              848
Financial Accounting Skills                893
Financial Management Skills                840
Java Programming Skills                    660
Leadership & Decision-Making Skills        840
Machine Learning Skills                    759
Marketing Skills                           840
Networking Skills                          660
Programming Logic Skills                   759
Python Programming Skills                  660
Software Engineering Skills                759
Strategic Planning Skills                  840
System Design Skills                       660
Taxation Skills                            893
Teaching Skills                            848
Web Development Skills                     660
English Communication & Writing Skills     921
Filipino Communication & Writing Skills    927
Risk Management Skills                     893
Innovation & Business Planning Skills      913
Consumer Behavior Analysis                 927
Sales Management Skills                    927
Artificial Intelligence Skills             759
Cybersecurity Skills                       660
dtype: int64

In [192]:
df.isna().mean() * 100

Gender                                      0.0
Age                                         0.0
Degree                                      0.0
Year Graduated                              0.0
CGPA                                        0.0
Average Prof Grade                          0.0
Average Elec Grade                          0.0
OJT Grade                                   0.0
Leadership POS                              0.0
Act Member POS                              0.0
Soft Skills Ave                             0.0
Hard Skills Ave                             0.0
Auditing Skills                            89.3
Budgeting & Analysis Skills                89.3
Classroom Management Skills                84.8
Cloud Computing Skills                     75.9
Curriculum Development Skills              84.8
Data Structures & Algorithms               75.9
Database Management Skills                 66.0
Educational Technology Skills              84.8
Financial Accounting Skills                89.3
Financial Management Skills                84.0
Java Programming Skills                    66.0
Leadership & Decision-Making Skills        84.0
Machine Learning Skills                    75.9
Marketing Skills                           84.0
Networking Skills                          66.0
Programming Logic Skills                   75.9
Python Programming Skills                  66.0
Software Engineering Skills                75.9
Strategic Planning Skills                  84.0
System Design Skills                       66.0
Taxation Skills                            89.3
Teaching Skills                            84.8
Web Development Skills                     66.0
English Communication & Writing Skills     92.1
Filipino Communication & Writing Skills    92.7
Risk Management Skills                     89.3
Innovation & Business Planning Skills      91.3
Consumer Behavior Analysis                 92.7
Sales Management Skills                    92.7
Artificial Intelligence Skills             75.9
Cybersecurity Skills                       66.0
dtype: float64

In [193]:
df.groupby("Degree").size()

Degree
BSA                      107
BSBA-Entrepreneurship     87
BSBA-Marketing            73
BSCS                     241
BSEd-English              79
BSEd-Filipino             73
BSIT                     340
dtype: int64

In [194]:
df = df.fillna(0)
df.isna().sum()

Gender                                     0
Age                                        0
Degree                                     0
Year Graduated                             0
CGPA                                       0
Average Prof Grade                         0
Average Elec Grade                         0
OJT Grade                                  0
Leadership POS                             0
Act Member POS                             0
Soft Skills Ave                            0
Hard Skills Ave                            0
Auditing Skills                            0
Budgeting & Analysis Skills                0
Classroom Management Skills                0
Cloud Computing Skills                     0
Curriculum Development Skills              0
Data Structures & Algorithms               0
Database Management Skills                 0
Educational Technology Skills              0
Financial Accounting Skills                0
Financial Management Skills                0
Java Programming Skills                    0
Leadership & Decision-Making Skills        0
Machine Learning Skills                    0
Marketing Skills                           0
Networking Skills                          0
Programming Logic Skills                   0
Python Programming Skills                  0
Software Engineering Skills                0
Strategic Planning Skills                  0
System Design Skills                       0
Taxation Skills                            0
Teaching Skills                            0
Web Development Skills                     0
English Communication & Writing Skills     0
Filipino Communication & Writing Skills    0
Risk Management Skills                     0
Innovation & Business Planning Skills      0
Consumer Behavior Analysis                 0
Sales Management Skills                    0
Artificial Intelligence Skills             0
Cybersecurity Skills                       0
dtype: int64

In [195]:
df.head()

,Gender,Age,Degree,Year Graduated,CGPA,Average Prof Grade,Average Elec Grade,OJT Grade,Leadership POS,Act Member POS,...,Teaching Skills,Web Development Skills,English Communication & Writing Skills,Filipino Communication & Writing Skills,Risk Management Skills,Innovation & Business Planning Skills,Consumer Behavior Analysis,Sales Management Skills,Artificial Intelligence Skills,Cybersecurity Skills
0,Female,22,BSIT,2021,1.96,83.15,82.90,84.31,No,No,...,0.0,96.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93.0
1,Female,21,BSIT,2021,3.41,83.83,84.81,81.60,No,No,...,0.0,79.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80.0
2,Female,23,BSIT,2021,2.44,95.16,88.31,76.36,No,No,...,0.0,87.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97.0
3,Female,22,BSEd-Filipino,2018,1.83,80.97,81.46,91.09,Yes,No,...,98.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Male,22,BSCS,2019,1.92,84.97,88.81,88.25,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0

In [196]:
from sklearn.preprocessing import LabelEncoder

In [197]:
encoder = LabelEncoder()
encoded_degree = encoder.fit_transform(df[["Degree"]])
encoded_gender = encoder.fit_transform(df[["Gender"]])
encoded_leadership_pos = encoder.fit_transform(df[["Leadership POS"]])
encoded_act_member_pos = encoder.fit_transform(df[["Act Member POS"]])

df['Degree'] = encoded_degree[:]
df['Gender'] = encoded_gender[:]
df['Leadership POS'] = encoded_leadership_pos[:]
df['Act Member POS'] = encoded_act_member_pos[:]
df.head(n=20)

F:\github-projects\alumni-employability\data\venv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
F:\github-projects\alumni-employability\data\venv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
F:\github-projects\alumni-employability\data\venv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
F:\github-projects\alumni-employability\data\venv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Gender,Age,Degree,Year Graduated,CGPA,Average Prof Grade,Average Elec Grade,OJT Grade,Leadership POS,Act Member POS,...,Teaching Skills,Web Development Skills,English Communication & Writing Skills,Filipino Communication & Writing Skills,Risk Management Skills,Innovation & Business Planning Skills,Consumer Behavior Analysis,Sales Management Skills,Artificial Intelligence Skills,Cybersecurity Skills
0,0,22,6,2021,1.96,83.15,82.90,84.31,0,0,...,0.0,96.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93.0
1,0,21,6,2021,3.41,83.83,84.81,81.60,0,0,...,0.0,79.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80.0
2,0,23,6,2021,2.44,95.16,88.31,76.36,0,0,...,0.0,87.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97.0
3,0,22,5,2018,1.83,80.97,81.46,91.09,1,0,...,98.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,22,3,2019,1.92,84.97,88.81,88.25,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0
5,1,22,4,2023,2.02,90.60,81.92,93.39,0,0,...,84.0,0.0,81.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0,24,3,2024,1.27,82.42,80.40,82.32,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0
7,0,23,0,2024,1.75,75.14,94.90,70.37,0,0,...,0.0,0.0,0.0,0.0,79.0,0.0,0.0,0.0,0.0,0.0
8,1,20,2,2023,1.96,82.67,76.04,82.18,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,98.0,84.0,0.0,0.0
9,1,21,6,2022,2.36,89.54,85.97,91.92,1,0,...,0.0,78.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0
10,1,23,0,2019,2.62,82.11,91.27,83.49,1,1,...,0.0,0.0,0.0,0.0,76.0,0.0,0.0,0.0,0.0,0.0
11,0,23,6,2018,1.94,86.41,73.33,86.45,0,0,...,0.0,94.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,91.0
12,1,22,2,2019,3.41,80.40,92.50,88.20,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,71.0,83.0,0.0,0.0
13,1,22,6,2022,2.37,92.99,79.46,84.76,0,0,...,0.0,74.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.0
14,1,21,6,2024,2.47,82.56,85.65,82.11,0,0,...,0.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,83.0
15,1,22,5,2023,1.14,90.72,84.16,82.92,0,1,...,78.0,0.0,0.0,87.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0,21,2,2018,2.02,90.10,100.00,85.66,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,80.0,73.0,0.0,0.0
17,1,22,6,2021,1.44,91.64,94.13,88.82,0,0,...,0.0,99.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,98.0
18,1,23,5,2024,1.75,93.56,76.24,76.74,0,1,...,78.0,0.0,0.0,74.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0,21,0,2023,2.76,91.38,90.99,73.08,0,1,...,0.0,0.0,0.0,0.0,87.0,0.0,0.0,0.0,0.0,0.0

In [198]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(df)
df['Employability'] = kmeans.labels_
df.head()

,Gender,Age,Degree,Year Graduated,CGPA,Average Prof Grade,Average Elec Grade,OJT Grade,Leadership POS,Act Member POS,...,Web Development Skills,English Communication & Writing Skills,Filipino Communication & Writing Skills,Risk Management Skills,Innovation & Business Planning Skills,Consumer Behavior Analysis,Sales Management Skills,Artificial Intelligence Skills,Cybersecurity Skills,Employability
0,0,22,6,2021,1.96,83.15,82.90,84.31,0,0,...,96.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93.0,0
1,0,21,6,2021,3.41,83.83,84.81,81.60,0,0,...,79.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80.0,0
2,0,23,6,2021,2.44,95.16,88.31,76.36,0,0,...,87.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97.0,0
3,0,22,5,2018,1.83,80.97,81.46,91.09,1,0,...,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,1,22,3,2019,1.92,84.97,88.81,88.25,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0,1

In [199]:
df['Employability'] = df['Employability'].map({0: 'Not Employable', 1: 'Employable'})

In [201]:
df.head(n=40)

,Gender,Age,Degree,Year Graduated,CGPA,Average Prof Grade,Average Elec Grade,OJT Grade,Leadership POS,Act Member POS,...,Web Development Skills,English Communication & Writing Skills,Filipino Communication & Writing Skills,Risk Management Skills,Innovation & Business Planning Skills,Consumer Behavior Analysis,Sales Management Skills,Artificial Intelligence Skills,Cybersecurity Skills,Employability
0,0,22,6,2021,1.96,83.15,82.90,84.31,0,0,...,96.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93.0,Not Employable
1,0,21,6,2021,3.41,83.83,84.81,81.60,0,0,...,79.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80.0,Not Employable
2,0,23,6,2021,2.44,95.16,88.31,76.36,0,0,...,87.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97.0,Not Employable
3,0,22,5,2018,1.83,80.97,81.46,91.09,1,0,...,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,Not Employable
4,1,22,3,2019,1.92,84.97,88.81,88.25,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0,Employable
5,1,22,4,2023,2.02,90.60,81.92,93.39,0,0,...,0.0,81.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Not Employable
6,0,24,3,2024,1.27,82.42,80.40,82.32,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0,Employable
7,0,23,0,2024,1.75,75.14,94.90,70.37,0,0,...,0.0,0.0,0.0,79.0,0.0,0.0,0.0,0.0,0.0,Not Employable
8,1,20,2,2023,1.96,82.67,76.04,82.18,0,1,...,0.0,0.0,0.0,0.0,0.0,98.0,84.0,0.0,0.0,Not Employable
9,1,21,6,2022,2.36,89.54,85.97,91.92,1,0,...,78.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.0,Not Employable
10,1,23,0,2019,2.62,82.11,91.27,83.49,1,1,...,0.0,0.0,0.0,76.0,0.0,0.0,0.0,0.0,0.0,Not Employable
11,0,23,6,2018,1.94,86.41,73.33,86.45,0,0,...,94.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,91.0,Not Employable
12,1,22,2,2019,3.41,80.40,92.50,88.20,1,1,...,0.0,0.0,0.0,0.0,0.0,71.0,83.0,0.0,0.0,Not Employable
13,1,22,6,2022,2.37,92.99,79.46,84.76,0,0,...,74.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.0,Not Employable
14,1,21,6,2024,2.47,82.56,85.65,82.11,0,0,...,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,83.0,Not Employable
15,1,22,5,2023,1.14,90.72,84.16,82.92,0,1,...,0.0,0.0,87.0,0.0,0.0,0.0,0.0,0.0,0.0,Not Employable
16,0,21,2,2018,2.02,90.10,100.00,85.66,1,1,...,0.0,0.0,0.0,0.0,0.0,80.0,73.0,0.0,0.0,Not Employable
17,1,22,6,2021,1.44,91.64,94.13,88.82,0,0,...,99.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,98.0,Not Employable
18,1,23,5,2024,1.75,93.56,76.24,76.74,0,1,...,0.0,0.0,74.0,0.0,0.0,0.0,0.0,0.0,0.0,Not Employable
19,0,21,0,2023,2.76,91.38,90.99,73.08,0,1,...,0.0,0.0,0.0,87.0,0.0,0.0,0.0,0.0,0.0,Not Employable
20,1,20,6,2022,3.12,76.69,70.00,92.65,0,0,...,99.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,87.0,Not Employable
21,1,20,5,2023,2.43,81.39,81.74,73.92,0,0,...,0.0,0.0,79.0,0.0,0.0,0.0,0.0,0.0,0.0,Not Employable
22,0,21,3,2021,2.07,81.62,92.94,90.63,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.0,0.0,Employable
23,1,22,6,2024,3.11,77.31,78.67,89.76,0,0,...,72.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95.0,Not Employable
24,1,20,0,2020,2.41,87.22,87.00,94.36,0,0,...,0.0,0.0,0.0,82.0,0.0,0.0,0.0,0.0,0.0,Not Employable
25,1,20,3,2024,1.95,80.80,90.18,86.33,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,81.0,0.0,Employable
26,1,22,3,2019,1.92,83.02,82.29,92.01,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,92.0,0.0,Employable
27,0,22,3,2020,3.22,83.21,84.26,84.20,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,78.0,0.0,Employable
28,1,21,4,2020,2.75,88.49,72.81,91.86,0,0,...,0.0,71.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Not Employable
29,0,23,3,2020,2.47,75.78,85.75,81.31,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,92.0,0.0,Employable
30,0,22,6,2020,1.85,85.89,78.53,88.17,0,0,...,73.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,98.0,Not Employable
31,0,20,6,2023,2.40,82.78,78.14,82.66,1,0,...,74.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,89.0,Not Employable
32,1,23,6,2018,1.62,79.98,75.85,83.04,0,0,...,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,Not Employable
33,1,23,5,2024,2.34,83.14,87.71,92.81,1,1,...,0.0,0.0,99.0,0.0,0.0,0.0,0.0,0.0,0.0,Not Employable
34,1,21,3,2018,2.63,76.23,93.12,83.61,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,89.0,0.0,Employable
35,1,22,6,2019,2.10,83.39,84.41,83.57,0,0,...,73.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.0,Not Employable
36,0,21,3,2024,3.20,84.58,84.86,91.84,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93.0,0.0,Employable
37,0,22,5,2019,1.19,73.67,87.60,79.81,0,0,...,0.0,0.0,73.0,0.0,0.0,0.0,0.0,0.0,0.0,Not Employable
38,1,22,3,2021,1.87,87.26,78.14,83.18,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0,Employable
39,1,22,6,2019,1.80,89.20,88.66,89.65,0,0,...,70.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,81.0,Not Employable

In [204]:
student_data = pd.read_csv("dataset/student-data-2.csv")
student_data['Employability'] = df['Employability']
student_data.head()

,Student Number,Gender,Age,Degree,Year Graduated,CGPA,Average Prof Grade,Average Elec Grade,OJT Grade,Leadership POS,...,Artificial Intelligence Skills,Cybersecurity Skills,Circuit Design Skills,Communication Systems Skills,Problem-Solving Skills,Clinical Skills,Patient Care Skills,Health Assessment Skills,Emergency Response Skills,Employability
0,25-00001,Female,22,BSIT,2021,1.96,83.15,82.90,84.31,No,...,NaN,93.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Employable
1,25-00002,Female,21,BSIT,2021,3.41,83.83,84.81,81.60,No,...,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Employable
2,25-00003,Female,23,BSIT,2021,2.44,95.16,88.31,76.36,No,...,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Employable
3,25-00004,Female,22,BSEd-Filipino,2018,1.83,80.97,81.46,91.09,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Employable
4,25-00005,Male,22,BSCS,2019,1.92,84.97,88.81,88.25,No,...,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employable